site :opscode

cookbook "apache2"
cookbook "mysql"
cookbook "init", path: "site-cookbooks/init"
cookbook "php", path: "site-cookbooks/php"
cookbook "yum_settings", path: "site-cookbooks/yum_settings"
cookbook "mysql_settings", path: "site-cookbooks/mysql_settings"
cookbook "yum"