site :opscode

cookbook "apache2"
cookbook "mysql"
cookbook "init", path: "site-cookbooks/init"
cookbook "php5.3", path: "site-cookbooks/php5.3"
cookbook "php5.4", path: "site-cookbooks/php5.4"
cookbook "php5.5", path: "site-cookbooks/php5.5"
cookbook "yum_settings", path: "site-cookbooks/yum_settings"
cookbook "mysql_settings", path: "site-cookbooks/mysql_settings"
cookbook "yum"